### ISSUE TITLE
Auto play feature is not present

### ISSUE THREAD

**Issue by abhinav2712** [arpanaditya/Sonic-Mix#3]
While using this app, and after completing one music, it didn't play the next one automatically and I had to press next.
It would be good if we add auto play feature which plays the next song after completing one song automatically like auto play feature on other apps.

**Comment by arpanaditya** [comment]
Hey, thanks for the suggestion. Do you want to work on this issue? @abhinav2712

**Comment by heysujal** [comment]
Hey I added this feature here https://github.com/arpanaditya/Sonic-Mix/pull/6

**Comment by arpanaditya** [comment]
Still, the issue is not resolved. Try again.

**Comment by heysujal** [comment]
Yes I will look into it.

**Comment by arpanaditya** [comment]
Yes, it's been done by @heysujal . You can check that now. :)
